name       : libvpx
version    : 1.6.0
release    : 3
source     :
    - http://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.6.0.tar.bz2 : d0afbb5eb1ecae68f8d578abace160a97e2e8a230e3028cf4db115d59a695aad
homepage   : http://www.webmproject.org/
license    : Public-Domain
component  : multimedia.codecs
summary    : Reference implementation of the VP8 codec
description: |
    Reference implementation of the VP8 codec
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
    - yasm
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ./configure --prefix=/usr --libdir=/usr/lib32 --disable-static --enable-shared --target=x86-linux-gcc
    else
        ./configure --prefix=/usr --disable-static --enable-shared --target=x86_64-linux-gcc
    fi
build      : |
    %make
install    : |
    %make_install
