name       : libvpx
version    : 1.8.1
release    : 7
source     :
    - https://github.com/webmproject/libvpx/archive/v1.8.1.tar.gz : df19b8f24758e90640e1ab228ab4a4676ec3df19d23e4593375e6f3847dee03e
homepage   : http://www.webmproject.org/
license    : MIT
component  : multimedia.codecs
summary    : Reference implementation of the VP8 & VP9 codec
description: |
    Reference implementation of the VP8 & VP9 codec
emul32     : yes
builddeps  :
    - yasm
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ./configure --prefix=/usr --libdir=/usr/lib32 --disable-static --enable-shared --target=x86-linux-gcc
    else
        ./configure --prefix=/usr --disable-static --enable-shared --target=x86_64-linux-gcc
    fi
build      : |
    %make
install    : |
    %make_install
