name        : libvpx
version     : 1.3.0
release     : 2
source      :
    - https://webm.googlecode.com/files/libvpx-v1.3.0.tar.bz2 : d3dcc8d84af51c6c382b214397c62402e37a799e8ebcda6f4217aef0010451a9
homepage    : http://www.webmproject.org/
license     : Public-Domain
component   : multimedia.codecs
summary     : Reference implementation of the VP8 codec
description : |
    Reference implementation of the VP8 codec
emul32     : yes
builddeps  :
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
    - yasm
setup      : |
    %patch -Np1 < $pkgfiles/gcc-5.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ./configure --prefix=/usr --libdir=/usr/lib32 --disable-static --enable-shared --target=x86-linux-gcc
    else
        ./configure --prefix=/usr --disable-static --enable-shared --target=x86_64-linux-gcc
    fi
build      : |
    %make
install    : |
    %make_install
