name       : libvpx
version    : 1.7.0
release    : 6
source     :
    - https://github.com/webmproject/libvpx/archive/v1.7.0.tar.gz : 1fec931eb5c94279ad219a5b6e0202358e94a93a90cfb1603578c326abfc1238
homepage   : http://www.webmproject.org/
license    : MIT
component  : multimedia.codecs
summary    : Reference implementation of the VP8 & VP9 codec
description: |
    Reference implementation of the VP8 & VP9 codec
emul32     : yes
builddeps  :
    - yasm
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ./configure --prefix=/usr --libdir=/usr/lib32 --disable-static --enable-shared --target=x86-linux-gcc
    else
        ./configure --prefix=/usr --disable-static --enable-shared --target=x86_64-linux-gcc
    fi
build      : |
    %make
install    : |
    %make_install
