name       : libvpx
version    : 1.12.0
release    : 16
source     :
    - https://github.com/webmproject/libvpx/archive/refs/tags/v1.12.0.tar.gz : f1acc15d0fd0cb431f4bf6eac32d5e932e40ea1186fe78e074254d6d003957bb
homepage   : http://www.webmproject.org/
license    : MIT
component  : multimedia.codecs
summary    : Reference implementation of the VP8 & VP9 codec
description: |
    Reference implementation of the VP8 & VP9 codec
emul32     : yes
optimize   : lto
builddeps  :
    - yasm
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        TARGET_CC=x86-linux-gcc
    else
        TARGET_CC=x86_64-linux-gcc
    fi

    ./configure \
        --disable-static \
        --disable-unit-tests \
        --enable-shared \
        --enable-vp9-highbitdepth \
        --enable-vp9-postproc \
        --enable-vp9-temporal-denoising \
        --libdir=%libdir% \
        --prefix=/usr \
        --target=$TARGET_CC
build      : |
    %make
install    : |
    %make_install
