name       : libvpx
version    : 1.6.1
release    : 5
source     :
    - http://storage.googleapis.com/downloads.webmproject.org/releases/webm/libvpx-1.6.1.tar.bz2 : 1c2c0c2a97fba9474943be34ee39337dee756780fc12870ba1dc68372586a819
homepage   : http://www.webmproject.org/
license    : Public-Domain
component  : multimedia.codecs
summary    : Reference implementation of the VP8 codec
description: |
    Reference implementation of the VP8 codec
emul32     : yes
builddeps  :
    - yasm
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-13194.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        ./configure --prefix=/usr --libdir=/usr/lib32 --disable-static --enable-shared --target=x86-linux-gcc
    else
        ./configure --prefix=/usr --disable-static --enable-shared --target=x86_64-linux-gcc
    fi
build      : |
    %make
install    : |
    %make_install
