name       : libvpx
version    : 1.10.0
release    : 12
source     :
    - https://github.com/webmproject/libvpx/archive/refs/tags/v1.10.0.tar.gz : 85803ccbdbdd7a3b03d930187cb055f1353596969c1f92ebec2db839fa4f834a
homepage   : http://www.webmproject.org/
license    : MIT
component  : multimedia.codecs
summary    : Reference implementation of the VP8 & VP9 codec
description: |
    Reference implementation of the VP8 & VP9 codec
emul32     : yes
builddeps  :
    - yasm
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        TARGET_CC=x86-linux-gcc
    else
        TARGET_CC=x86_64-linux-gcc
    fi

    ./configure \
        --disable-static \
        --disable-unit-tests \
        --enable-shared \
        --enable-vp9-highbitdepth \
        --enable-vp9-postproc \
        --enable-vp9-temporal-denoising \
        --libdir=%libdir% \
        --prefix=/usr \
        --target=$TARGET_CC
build      : |
    %make
install    : |
    %make_install
