name       : libvpx
version    : 1.8.2
release    : 9
source     :
    - https://github.com/webmproject/libvpx/archive/v1.8.2.tar.gz : 8735d9fcd1a781ae6917f28f239a8aa358ce4864ba113ea18af4bb2dc8b474ac
homepage   : http://www.webmproject.org/
license    : MIT
component  : multimedia.codecs
summary    : Reference implementation of the VP8 & VP9 codec
description: |
    Reference implementation of the VP8 & VP9 codec
emul32     : yes
builddeps  :
    - yasm
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export TARGET_CC=x86-linux-gcc
    else
        export TARGET_CC=x86_64-linux-gcc
    fi

    ./configure \
        --disable-static \
        --disable-unit-tests \
        --enable-shared \
        --enable-vp9-highbitdepth \
        --enable-vp9-postproc \
        --enable-vp9-temporal-denoising \
        --libdir=%libdir% \
        --prefix=/usr \
        --target=$TARGET_CC
build      : |
    %make
install    : |
    %make_install
